version: '3.8'

services:
  db:
    image: mysql:8
    container_name: paymybuddy_db
    environment:
      MYSQL_ROOT_PASSWORD: "__DB_ROOT_PASSWORD__"
      MYSQL_DATABASE: "paymybuddy"
      MYSQL_USER: "__DB_USER__"
      MYSQL_PASSWORD: "__DB_PASSWORD__"
    ports:
      - "3306:3306"

  app:
    image: __DOCKER_IMAGE__
    container_name: paymybuddy_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: paymybuddy
      DB_USER: "__DB_USER__"
      DB_PASSWORD: "__DB_PASSWORD__"
    ports:
      - "80:5000"
