version: '3.8'

services:
  db:
    image: mysql:8
    container_name: paymybuddy_db
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_DATABASE: "paymybuddy"
      MYSQL_USER: "paymybuddy"
      MYSQL_PASSWORD: "secretpassword"
    ports:
      - "3306:3306"
    volumes:
      - ./init_data-base/create.sql:/docker-entrypoint-initdb.d/create.sql

  app:
    image: rootcfk/paymybuddy:latest
    container_name: paymybuddy_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: paymybuddy
      DB_USER: "paymybuddy"
      DB_PASSWORD: "secretpassword"
    ports:
      - "80:5000"
