version: '3.1'
services:
  paymybuddy:
    image: ${DOCKERHUB_AUTH}/paymybuddy:latest
    container_name: paymybuddy
    restart: always
    env_file:
      - env/paymybuddy.env
    environment:
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:mysql://paymybuddydb:3306/paymybuddy
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - paymybuddydb
    ports:
      - "8080:8080"
    networks:
      - paymybuddynetwork

  paymybuddydb:
    image: mysql:latest
    container_name: paymybuddydb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: paymybuddy
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_paymybuddy:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - paymybuddynetwork

volumes:
  db_paymybuddy:

networks:
  paymybuddynetwork:
    driver: bridge
