version: '3.8'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: db_paymybuddy
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"   # Si besoin aussi pour la DB
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: "${DOCKER_IMAGE}"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db_paymybuddy
      SPRING_DATASOURCE_USERNAME: "${MYSQL_USER}"
      SPRING_DATASOURCE_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "80:5000"
    depends_on:
      - db

volumes:
  db_data:
