version: '3.8'

services:
  paymybuddy-backend:
    build: .
    container_name: paymybuddy-backend
    restart: always
    depends_on:
      paymybuddy-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://paymybuddy-db:3306/paymybuddy
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - paymybuddy-network

  paymybuddy-db:
    image: mysql:8.0
    container_name: paymybuddy-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: paymybuddy
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - paymybuddy_mysql_data:/var/lib/mysql
    networks:
      - paymybuddy-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s

volumes:
  paymybuddy_mysql_data:

networks:
  paymybuddy-network:
    driver: bridge
