version: '3.8'

services:
  db:
    image: mysql:8
    container_name: paymybuddy_db
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password.txt
      MYSQL_DATABASE: paymybuddy
      MYSQL_USER_FILE: /run/secrets/db_user.txt
      MYSQL_PASSWORD_FILE: /run/secrets/db_password.txt
    secrets:
      - db_user.txt
      - db_password.txt
      - db_root_password.txt
    ports:
      - "3306:3306"

  app:
    image: ${DOCKERHUB_AUTH}/${IMAGE_NAME}:${IMAGE_TAG}
    container_name: paymybuddy_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: paymybuddy
      DB_USER_FILE: /run/secrets/db_user.txt
      DB_PASSWORD_FILE: /run/secrets/db_password.txt
    secrets:
      - db_user.txt
      - db_password.txt
    ports:
      - "80:5000"

secrets:
  db_user.txt:
    file: ./secrets/db_user.txt
  db_password.txt:
    file: ./secrets/db_password.txt
  db_root_password.txt:
    file: ./secrets/db_root_password.txt
