version: '3.8'

services:
  db:
    image: mysql:8
    container_name: paymybuddy_db
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/db_root_password.txt
      MYSQL_DATABASE: paymybuddy
      MYSQL_USER: ${DB_USER_PLACEHOLDER}
      MYSQL_PASSWORD: ${DB_PASSWORD_PLACEHOLDER}
    ports:
      - "3306:3306"

  app:
    image: ${DOCKERHUB_AUTH}/${IMAGE_NAME}:${IMAGE_TAG}
    container_name: paymybuddy_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: paymybuddy
      DB_USER: ${DB_USER_PLACEHOLDER}
      DB_PASSWORD: ${DB_PASSWORD_PLACEHOLDER}
    ports:
      - "80:5000"
